spring:
  application:
    name: desafio04
  datasource:
    url: jdbc:postgresql://localhost:5432/<Nome-do-database-usado-no-desafio03>
    username: <Username-do-database-usado-no-desafio03>
    password: <Password-do-database-usado-no-desafio03>
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
